version: "3.7"

services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    networks:
      - backend
  auth:
    build: ./auth
    restart: always
    hostname: auth
    ports:
      - ${AUTH_SERVICE_PORT}:${AUTH_SERVICE_PORT}
    environment:
      - MONGO_DSN=${MONGO_DSN}
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
  todo:
    build: ./todo
    restart: always
    hostname: todo
    ports:
      - ${TODO_SERVICE_PORT}:${TODO_SERVICE_PORT}
    environment:
      - MONGO_DSN=${MONGO_DSN}
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
  db:
    image: 'mongo:3.7'
    restart: always
    volumes:
      - "./db/data/db-files:/data/db"
    ports:
      - 27017:27017
    networks:
      - backend
networks:
  backend:
    driver: bridge
